server:
  error:
    whitelabel:
      enabled: true
  servlet:
    encoding:
      force: true

spring:
  datasource:
    initialization-mode: embedded
  messages:
    always-use-message-format: false
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: "dev"
  resources:
    add-mappings: false
  redis:
    host: 127.0.0.1
    database: 15
wshen:
  jwt:
    access-token-expire-time: 300000
    refresh-token-expire-time: 2592000000
  redisson:
    config:
      singleServerConfig:
        address: redis://127.0.0.1:6379

